- name: Install required packages
  apt:
    pkg:
    - libcairo2-dev
    - libjpeg-dev
    - libgif-dev
    - redis-server
    update_cache: yes
    state: latest
  become: yes
  tags:
    - setup

- name: Git Clone Repo
  git:
    repo: "{{ repo }}"
    dest: "{{ home_directory }}/{{ app }}"
    force: yes
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  npm:
    path: "{{ home_directory }}/{{ app }}"
    unsafe_perm: yes
    production: yes
  register: npm_finished
  when: git_clone_app_finished.changed
  tags:
    - setup
    - update

- name: Add production conf
  template:
    src: production.json.tpl
    dest: "{{ home_directory }}/{{ app }}/config/production.json"
  tags:
    - setup

# Install and run MRISA server for reverse image search
- import_tasks: mrisa.yml

- name: Stop app
  command: forever stop "{{ app }}"
  ignore_errors: yes
  tags:
    - restart
    - stop
    - update

- name: Start app
  command:
    cmd: forever start -a --uid "{{ app }}" bin/www
    chdir: "{{ home_directory }}/{{ app }}"
  environment:
    NODE_ENV: production
    PORT: "{{ app_port }}"
  tags:
    - restart
    - start
    - update
