home_directory: "/home/{{ ansible_user }}"

mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_databases:
  - name: mattermost
mysql_users:
  - name: mmuser
    host: "%"
    password: "{{ vault_mysql_user_mmuser_password }}"
    priv: "mattermost.*:ALL"

certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: matti.schneider@diplomatie.gouv.fr
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user }}"
certbot_auto_renew_hour: "4"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--no-random-sleep-on-renew --nginx --nginx-ctl /usr/sbin/nginx --nginx-server-root /etc/nginx/"
certbot_certs:
  - email: matti.schneider@diplomatie.gouv.fr
    domains:
      - "{{ inventory_hostname }}"
