- name: Git Clone Repo
  git:
    repo: "{{ repo }}"
    dest: "{{ home_directory }}/{{ app }}"
    force: yes
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  npm:
    path: "{{ home_directory }}/{{ app }}"
    unsafe_perm: yes
    production: yes
  register: npm_finished
  when: git_clone_app_finished.changed
  tags:
    - setup
    - update

- name: Creates config directory
  file:
    path: "{{ home_directory }}/{{ app }}/config"
    state: directory
  tags:
    - setup

- name: Creates db directory
  file:
    path: "{{ home_directory }}/{{ app }}/app/rss/db"
    state: directory
  tags:
    - setup

- name: Add default conf
  template:
    src: default.json.tpl
    dest: "{{ home_directory }}/{{ app }}/config/default.json"
  tags:
    - setup

- name: Stop APP
  command: forever stop "{{ app }}"
  ignore_errors: yes
  tags:
    - restart
    - stop
    - update

- name: Start APP
  command:
    cmd: forever start -a --uid "{{ app }}" index.js
    chdir: "{{ home_directory }}/{{ app }}"
  environment:
    NODE_ENV: production
    PORT: "{{ app_port }}"
  tags:
    - restart
    - start
    - update
