all:
  children:
    production:
      hosts:
        51.89.231.68:
          ansible_user: debian
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          ansible_python_interpreter: /usr/bin/python3
          base_url: https://disinfo.quaidorsay.fr
          enable_https: true
