---
- name: Setup disinfo.quaidorsay.fr infra
  hosts: all
  become: yes

- import_playbook: infra/common.yml
- import_playbook: infra/certbot.yml
- import_playbook: infra/mysql.yml
- import_playbook: infra/nginx.yml
- import_playbook: infra/mattermost.yml
- import_playbook: infra/node.yml
- import_playbook: infra/mongodb.yml
