- name: Git Clone Repo
  git:
    repo: "{{ repo }}"
    dest: "{{ home_directory }}/{{ app }}"
    force: yes
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  npm:
    path: "{{ home_directory }}/{{ app }}"
    unsafe_perm: yes
  when: git_clone_app_finished.changed
  tags:
    - setup
    - update

- name: Build app
  command:
    cmd: npm run build
    chdir: "{{ home_directory }}/{{ app }}"
  tags:
    - setup
    - update
